<?php

use App\Models\Pengiriman;
use Illuminate\Database\Seeder;

class PengirimanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pengiriman::insert([
                [
                    'nomor_invoice' => 'CSM-INV00000001',
                    'tanggal' => '2019-05-02',
                    'perusahaan_asal' => 'Cyberlabs',
                    'alamat_asal' => 'bandung',
                    'kota_asal_id' => 22,
                    'provinsi_asal_id' => 9,
                    'nomor_telepon_asal' => '081223230946',
                    'kode_pos_asal' => '40288',
                    'negara_asal' => 'indonesia',
                    'perusahaan_tujuan' => 'laskar teknologi mulia',
                    'alamat_tujuan' => 'batam',
                    'kota_tujuan_id' => 90,
                    'provinsi_tujuan_id' => 4,
                    'nomor_telepon_tujuan' => '081345088521',
                    'kode_pos_tujuan' => '40257',
                    'negara_tujuan' => 'indonesia',
                    'jalur' => 0,
                    'paket' => 1,
                    'jenis_barang' => 'dokumen',
                    'jenis_berat' => 1,
                    'harga' => 25000,
                    'berat' => 20,
                    'panjang' => 32,
                    'lebar' => 10,
                    'tinggi' => 20,
                    'asuransi' => 90000,
                    'koli' => 1,
                    'sub_charge' => 25,
                    'ongkos_kirim' =>  23000
                ],
                [
                    'nomor_invoice' => 'CSM-INV00000002',
                    'tanggal' => '2019-05-02',
                    'perusahaan_asal' => 'Atom Rekadaya Cipta',
                    'alamat_asal' => 'bandung',
                    'kota_asal_id' => 22,
                    'provinsi_asal_id' => 9,
                    'nomor_telepon_asal' => '081223230946',
                    'kode_pos_asal' => '40288',
                    'negara_asal' => 'indonesia',
                    'perusahaan_tujuan' => 'laskar teknologi mulia',
                    'alamat_tujuan' => 'batam',
                    'kota_tujuan_id' => 90,
                    'provinsi_tujuan_id' => 4,
                    'nomor_telepon_tujuan' => '081345088521',
                    'kode_pos_tujuan' => '40257',
                    'negara_tujuan' => 'indonesia',
                    'jalur' => 0,
                    'paket' => 1,
                    'jenis_barang' => 'dokumen',
                    'harga' => 25000,
                    'berat' => 20,
                    'jenis_berat' => 0,
                    'panjang' => 32,
                    'lebar' => 10,
                    'tinggi' => 20,
                    'asuransi' => 90000,
                    'koli' => 1,
                    'sub_charge' => 25,
                    'ongkos_kirim' =>  23000
                ],
                [
                    'nomor_invoice' => 'CSM-INV00000003',
                    'tanggal' => '2019-05-02',
                    'perusahaan_asal' => 'CV saudagar muda',
                    'alamat_asal' => 'bandung',
                    'kota_asal_id' => 22,
                    'provinsi_asal_id' => 9,
                    'nomor_telepon_asal' => '081223230946',
                    'kode_pos_asal' => '40288',
                    'negara_asal' => 'indonesia',
                    'perusahaan_tujuan' => 'laskar teknologi mulia',
                    'alamat_tujuan' => 'batam',
                    'kota_tujuan_id' => 90,
                    'provinsi_tujuan_id' => 4,
                    'nomor_telepon_tujuan' => '081345088521',
                    'kode_pos_tujuan' => '40257',
                    'negara_tujuan' => 'indonesia',
                    'jalur' => 0,
                    'paket' => 1,
                    'jenis_barang' => 'dokumen',
                    'harga' => 25000,
                    'berat' => 20,
                    'panjang' => 32,
                    'lebar' => 10,
                    'tinggi' => 20,
                    'asuransi' => 90000,
                    'koli' => 1,
                    'jenis_berat' => 1,
                    'sub_charge' => 25,
                    'ongkos_kirim' =>  23000
                ],
                [
                    'nomor_invoice' => 'CSM-INV00000004',
                    'tanggal' => '2019-05-02',
                    'perusahaan_asal' => 'PT Tali saudara',
                    'alamat_asal' => 'bandung',
                    'kota_asal_id' => 22,
                    'provinsi_asal_id' => 9,
                    'nomor_telepon_asal' => '081223230946',
                    'kode_pos_asal' => '40288',
                    'negara_asal' => 'indonesia',
                    'perusahaan_tujuan' => 'laskar teknologi mulia',
                    'alamat_tujuan' => 'batam',
                    'kota_tujuan_id' => 90,
                    'provinsi_tujuan_id' => 4,
                    'nomor_telepon_tujuan' => '081345088521',
                    'kode_pos_tujuan' => '40257',
                    'negara_tujuan' => 'indonesia',
                    'jalur' => 0,
                    'paket' => 1,
                    'jenis_barang' => 'dokumen',
                    'harga' => 25000,
                    'berat' => 20,
                    'panjang' => 32,
                    'lebar' => 10,
                    'tinggi' => 20,
                    'asuransi' => 90000,
                    'jenis_berat' => 0,
                    'koli' => 1,
                    'sub_charge' => 25,
                    'ongkos_kirim' =>  23000
                ],
                [
                    'nomor_invoice' => 'CSM-INV00000005',
                    'tanggal' => '2019-05-02',
                    'perusahaan_asal' => 'PT Umati',
                    'alamat_asal' => 'bandung',
                    'kota_asal_id' => 22,
                    'provinsi_asal_id' => 9,
                    'nomor_telepon_asal' => '081223230946',
                    'kode_pos_asal' => '40288',
                    'negara_asal' => 'indonesia',
                    'perusahaan_tujuan' => 'laskar teknologi mulia',
                    'alamat_tujuan' => 'batam',
                    'kota_tujuan_id' => 90,
                    'provinsi_tujuan_id' => 4,
                    'nomor_telepon_tujuan' => '081345088521',
                    'kode_pos_tujuan' => '40257',
                    'negara_tujuan' => 'indonesia',
                    'jalur' => 0,
                    'paket' => 1,
                    'jenis_barang' => 'dokumen',
                    'harga' => 25000,
                    'jenis_berat' => 0,
                    'berat' => 20,
                    'panjang' => 32,
                    'lebar' => 10,
                    'tinggi' => 20,
                    'asuransi' => 90000,
                    'koli' => 1,
                    'sub_charge' => 25,
                    'ongkos_kirim' =>  23000
                ],
            ]
        );
    }
}
